services:
  #traefik:
  #  image: traefik:v3.0
  #  command:
  #    - "--api.insecure=true"
  #    - "--api.dashboard=true"
  #    - "--providers.docker=true"
  #    - "--providers.docker.exposedbydefault=false"
  #    - "--entrypoints.web.address=:80"
  #  ports:
  #    - "80:80"     # Public entrypoint
  #    - "8082:8080"   # Traefik dashboard (optional)
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock:ro
  #  networks:
  #    - shared_network
    

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Vite's default dev port is 5173
      
    volumes:
      - ./frontend:/app           # Syncs your code
      - /app/node_modules         # Prevents local modules from overwriting container modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Necessary for WSL/Docker to detect file saves
    command: npm run dev
    env_file: "frontend.env"
    networks:
      - shared_network
    

  architecture-retrieval:
    build: 
      context: ./architecture-retrieval
      dockerfile: Dockerfile 
    ports:  
      - "8000:8000"
    volumes:
      # Match the Dockerfile WORKDIR
      - nix_data:/nix
      - ./architecture-retrieval:/api
      - ./repositories/downloads:/api/downloads
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Lisbon
      - DOCKER_API_VERSION=1.41
      
    env_file:
      - ./architecture-retrieval/.env
    user: "1000:1000"
    group_add:
      - "998"
    networks:
      - shared_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.arch.rule=Host(`architecture.localhost`)"
      - "traefik.http.services.arch.loadbalancer.server.port=8000"

  code2dfd:
    build: 
      context: ./code2DFD
      dockerfile: Dockerfile 
    ports:  
      - "5001:5001" # Assuming your backend runs on port 5001
    volumes:
      - ./code2DFD:/app
      - ./repositories/downloads:/app/downloads
    env_file:
      - dev.env
    networks:
      - shared_network
volumes:
  nix_data:
networks:
  shared_network:
    name: shared_network
    external: true