services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Vite's default dev port is 5173
    volumes:
      - ./frontend:/app           # Syncs your code
      - /app/node_modules         # Prevents local modules from overwriting container modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Necessary for WSL/Docker to detect file saves
    command: npm run dev
    env_file: "frontend.env"

  architecture-retrieval:
    build: 
      context: ./architecture-retrieval
      dockerfile: Dockerfile 
    ports:  
      - "8000:8000" # Assuming your backend runs on port 8000
    volumes:
      - ./architecture-retrieval:/app
      - /home/joca/Thesis/repositories/downloads:/api/downloads
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.41 # Optional: helps Go SDK negotiate version
    env_file:
      - ./architecture-retrieval/.env
    # TODO: In production, it shouldn't run as root. You can set a specific user or use a non-root image.
    user: "1000:1000"
    group_add:
      - "998"
    stop_grace_period: 20s # Give it more time to clean up containers on shutdown

  # You can add your backend service here later
  # backend:
  #   build: ./backend
  #   ...

networks:
  app-network:
    driver: bridge
    name: vivactor_micro_network